#!/bin/zsh
zmodload zsh/complist
autoload -Uz _dirstack_
zle -C _dirstack_ menu-select _dirstack_

_dirstack() {
  setopt localoptions $_edit_opts

  LBUFFER="${LBUFFER%%\~-<->}~"
  if [[ $WIDGET == *-plus ]]; then
    LBUFFER+='+'
  else
    LBUFFER+='-'
  fi

  local -a dirstack=( $dirstack[1,16] )

  zle _dirstack_

  case $_lastcomp[nmatches] in
    0 )
      BUFFER=''
      zle .get-line
      return 1
      ;;
    1 )
      zle .accept-line
      return 0
      ;;
    * )
      return 0
      ;;
  esac
}

_dirstack "$@"
