#!/bin/zsh
zmodload zsh/complist
autoload -Uz _dirstack_
zle -C _dirstack_ menu-select _dirstack_

_dirstack() {
  setopt localoptions $_edit_opts

  if [[ $LASTWIDGET != $WIDGET ]]; then
    zle .push-line
    if [[ -o autocd ]]; then
      LBUFFER='~'
    else
      LBUFFER='cd '
    fi
    if [[ -o pushdminus ]]; then
      LBUFFER+='-'
    else
      LBUFFER+='+'
    fi
  fi

  local -a dirstack=( $dirstack[1,16] )

  zle _dirstack_

  case $_lastcomp[nmatches] in
    0 )
      BUFFER=''
      zle .get-line
      return 1
      ;;
    1 )
      zle .accept-line
      return 0
      ;;
    * )
      return 0
      ;;
  esac
}

_dirstack "$@"
