#!/bin/zsh
zmodload -F zsh/parameter p:functions

_execute_cmd.inner() {
  # Prevent ALRM traps from redrawing the prompt too early.
  setopt localtraps
  trap '' ALRM
  TRAPALARM() {}

  print -rS -- "$WIDGET"  # Save command in history.
  builtin fc -W		        # Write history to file (for HIST_SAVE_NO_DUPS).
  zle -I
  eval "$WIDGET"
}

_execute_cmd() {
  _execute_cmd.inner "$@"

  # Restart ALRM timeout, if any.
  (( TMOUT )) && [[ "$( trap )" == *ALRM* || -v functions[TRAPALARM] ]] &&
      kill -ALRM $$
}

_execute_cmd "$@"
