#!/bin/zsh
zmodload zsh/complist

_show_clipboard() {
  local displ=( "$CUTBUFFER" $killring[@] )
  compadd -V kill-ring -ld displ -QU - $CUTBUFFER $killring[@]

  compstate[insert]=''
  compstate[list]='list force'
  compstate[list_max]=0
  (( compstate[nmatches] > 0 ))
}

_show_clipboard "$@"
