#!/bin/zsh

_show_clipboard() {
  setopt $_edit_opts

  local displ=( "$CUTBUFFER" $killring[@] )
  compadd -V kill-ring -QU -ld displ - $CUTBUFFER $killring[@]

  compstate[insert]=''
  compstate[list]='list force'
  compstate[list_max]=0
  (( compstate[nmatches] > 0 ))
}

zmodload zsh/complist

_show_clipboard "$@"
