#!/bin/zsh

_show_clipboard() {
  setopt $_edit_opts

  export ZLS_COLORS="=${(b)BUFFER[YANK_START+1,YANK_END]}=$color[bold]"

  local displ=( "$CUTBUFFER" $killring[@] )
  compadd -V kill-ring -QU -ld displ - $CUTBUFFER $killring[@]

  compstate[insert]=''
  compstate[list]='list force'
  compstate[list_max]=0
  (( compstate[nmatches] > 0 ))
}

setopt $_edit_opts
zmodload zsh/complist
autoload -Uz colors
colors

_show_clipboard "$@"
