#!/bin/zsh
setopt $_edit_opts

local subword="([[:WORD:]]##~*[[:lower:]]*[[:upper:]]*)"
local nonword='[^[:WORD:]]#'

if [[ $WIDGET == *backward-* ]]; then
  (( MARK = CURSOR - ${(M)#LBUFFER%%$~subword$~nonword} ))
else
  (( MARK = CURSOR + ${(M)#RBUFFER##$~nonword$~subword} ))
fi

(( MARK != CURSOR ))
local -i ret=$?

if [[ $WIDGET == *kill-* ]]; then
  zle .kill-region
  zle -f kill
else
  (( CURSOR = MARK ))
fi
unset MARK

return ret
