#!/bin/zsh
setopt $_edit_opts

local subword="([[:WORD:]]##~*[[:lower:]]*[[:upper:]]*~*[[:alnum:]]*[^[:alnum:]]*)"
local nonword='([[:punct:][:space:]]##)'

local +h -i MARK
if [[ $WIDGET == *backward-* ]]; then
  (( MARK = CURSOR - ${(M)#LBUFFER%%($~subword|$~nonword~*[[:space:]]*[[:punct:]]*)(?|)} ))
else
  (( MARK = CURSOR + ${(M)#RBUFFER##(?|)($~subword|$~nonword~*[[:punct:]]*[[:space:]]*)} ))
fi

(( MARK != CURSOR ))
local -i ret=$?

if [[ $WIDGET == *kill-* ]]; then
  zle .kill-region
  zle -f kill
else
  (( CURSOR = MARK ))
fi

return ret
