#!/bin/zsh

visual-yank() {
  setopt $_edit_opts

  local -i len=$#killring[@]
  local -aU kills=( "$CUTBUFFER" $killring[@] )
  shift kills
  {
    killring=( $kills[@] )

    if [[ $WIDGET == reverse-* ]]; then
      local widget=.${WIDGET#reverse-}
      local -i i; for (( i = 0; i < $#kills[@]; i++ )); do
        zle $widget
      done
    else
      zle .$WIDGET
    fi

    zle -f yank
    zle _show_clipboard
  } always {
    killring+=( "${(s:.:@)${(r:$((len - $#killring[@] - 1))::.:):-}}" )
  }
}

autoload -Uz _show_clipboard
zle -C _show_clipboard list-choices _show_clipboard

visual-yank "$@"
